version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "8000:80"
    volumes:
      - ./Backend:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seminario
    ports:
      - "3306:3306"

 # frontend:
  #  build: ./Frontend
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./Frontend:/app
#    stdin_open: true